# fly.toml app configuration file generated for tldrive on 2023-04-28T00:35:23+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "teledrivehasanislam511" #your app name
kill_signal = "SIGINT"
kill_timeout = 5
primary_region = "sin" #your region
processes = []

[build]

[env]
  docker/.env
[experimental]
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 4000 #internal port
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443
